phrases = [
  "let's circle back",
  'put a pin in that',
  'circle the wagons',
  'the learnings',
  'the asks',
  'think outside the box',
  'take this offline',
  'move the needle',
  'top of mind',
  "let's double click on that",
  'north star',
  '10x',
  'alright, is everyone here?',
  'get aligned',
  'right out of the gate',
  'super excited',
  'sync up with',
  'drain the slide'
]
